# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 20:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('START', 'Start'), ('END', 'End')], max_length=50)),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'date',
                'verbose_name_plural': 'dates',
            },
        ),
        migrations.CreateModel(
            name='DescriptionAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('body', models.TextField()),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'description',
                'verbose_name_plural': 'descriptions',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DEPARTMENT', 'Department'), ('EMPLOYEE', 'Employee'), ('MEMBER', 'Member')], default='DEPARTMENT', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name_last', models.CharField(max_length=200)),
                ('name_first', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('WEBSITE', 'Website'), ('BOOK', 'Book'), ('TOOL', 'Tool')], default='WEBSITE', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 22, 20, 20, 25, 584231, tzinfo=utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 22, 20, 20, 37, 957737, tzinfo=utc), verbose_name='Modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='example', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='collection.Organization'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='collection.Organization'),
        ),
        migrations.AddField(
            model_name='descriptionattr',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Work'),
        ),
        migrations.AddField(
            model_name='dateattr',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Work'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='collection.OrganizationMembership', to='collection.Organization'),
        ),
    ]
