# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BEGIN', 'Begin Date'), ('END', 'End Date'), ('ACCESSED', 'Last Accessed Date')], default='PRIMARY', max_length=50)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptionAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('BEGIN', 'Begin Date'), ('END', 'End Date'), ('ACCESSED', 'Last Accessed Date')], default='PRIMARY', max_length=50)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField()),
                ('body', models.TextField()),
                ('content_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'ordering': ['sequence', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('name_last', models.CharField(max_length=200)),
                ('name_first', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
