# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='month',
            field=models.IntegerField(blank=True),
        ),
    ]
