# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='object_id',
        ),
    ]
