# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160721_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('DEPARTMENT', 'Department'), ('EMPLOYEE', 'Employee'), ('MEMBER', 'Member')], default='DEPARTMENT', max_length=50)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='collection.Entity')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='collection.Entity')),
            ],
        ),
        migrations.AddField(
            model_name='entity',
            name='members',
            field=models.ManyToManyField(through='collection.Membership', to='collection.Entity'),
        ),
    ]
