# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_organization_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('category', models.CharField(choices=[('ARCHIVE', 'archive'), ('LIBRARY', 'library'), ('MUSEUM', 'museum')], default='LIBRARY', help_text='What type of organization?', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='categories',
            field=models.ManyToManyField(to='collection.OrganizationCategory'),
        ),
    ]
