# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160722_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgOrgRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DEPARTMENT', 'Department'), ('MEMBER', 'Member')], default='DEPARTMENT', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='child',
        ),
        migrations.RemoveField(
            model_name='organizationmembership',
            name='parent',
        ),
        migrations.AlterField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(through='collection.OrgOrgRelationship', to='collection.Organization'),
        ),
        migrations.DeleteModel(
            name='OrganizationMembership',
        ),
        migrations.AddField(
            model_name='orgorgrelationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='collection.Organization'),
        ),
        migrations.AddField(
            model_name='orgorgrelationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='collection.Organization'),
        ),
    ]
