# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_dateattr_descriptionattr_organization_person_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateattr',
            name='content_type',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='descriptionattr',
            name='content_type',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
