# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160717_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_begin',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_end',
        ),
    ]
