# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20160713_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
