# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20160718_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptionattr',
            name='category',
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='category',
            field=models.CharField(choices=[('INCORPORATED', 'Incorporation'), ('TERMINATED', 'Termination'), ('BEGUN', 'Birth'), ('ENDED', 'Death'), ('ACCESSED', 'Last Accessed')], max_length=50),
        ),
    ]
