# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20160802_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='nonprofit',
            field=models.BooleanField(default=True, help_text='Select whether or not this organization is organized as a not-for-profit entity.'),
        ),
        migrations.AlterField(
            model_name='organizationcategory',
            name='category',
            field=models.CharField(choices=[('ARCHIVE', 'archive'), ('CONSORTIUM', 'consortium'), ('CORPORATION', 'corporation'), ('LIBRARY', 'library'), ('MUSEUM', 'museum'), ('SCHOOL', 'school')], default='LIBRARY', help_text='What type of organization?', max_length=50, unique=True),
        ),
    ]
