# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20160722_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='members',
            new_name='related_organizations',
        ),
    ]
