# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20160717_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='accessed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
