# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collection', '0004_auto_20160802_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltNameAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('object_id', models.PositiveIntegerField(help_text='Provide the actual object ID of the generic relation within the table of the Content Type.')),
                ('name', models.CharField(help_text="Select an alternate Name, e.g. the abbreviation 'OCLC'.", max_length=200)),
                ('category', models.CharField(choices=[('ABBREVIATION', 'abbreviation'), ('NICKNAME', 'nickname')], default='ABBREVIATION', help_text='In what category is this name?', max_length=50)),
                ('content_type', models.ForeignKey(help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'alternate name',
                'verbose_name_plural': 'alternate names',
            },
        ),
    ]
