# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20160719_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='source',
            name='slug',
        ),
    ]
