# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20160717_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateattr',
            old_name='source_accessed',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='day',
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='month',
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='year',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='source_accessed',
        ),
        migrations.AddField(
            model_name='dateattr',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='PRIMARY', max_length=50),
        ),
        migrations.AddField(
            model_name='descriptionattr',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary')], default='PRIMARY', max_length=50),
        ),
    ]
