# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20160717_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='accessed',
        ),
        migrations.AddField(
            model_name='source',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
