# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20160722_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('content_type', models.CharField(choices=[('WEBSITE', 'website'), ('BOOK', 'book')], max_length=50)),
                ('book', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Book')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='orgorgrelationship',
            options={'verbose_name': 'organization relationship'},
        ),
        migrations.AlterModelOptions(
            name='orgpersonrelationship',
            options={'verbose_name': 'member'},
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='descriptionattr',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='related_people',
            field=models.ManyToManyField(related_name='organizations', through='collection.OrgPersonRelationship', to='collection.Person'),
        ),
        migrations.AlterField(
            model_name='orgorgrelationship',
            name='category',
            field=models.CharField(choices=[('DEPARTMENT', 'is department of'), ('LOCATED', 'is located in'), ('MEMBER', 'is member of'), ('OWNED', 'is owned by'), ('PART', 'is part of')], default='DEPARTMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='orgpersonrelationship',
            name='category',
            field=models.CharField(choices=[('EMPLOYED', 'is employed by'), ('CREATOR', 'is creator of'), ('MEMBER', 'is member of')], default='EMPLOYED', max_length=50),
        ),
        migrations.AlterField(
            model_name='orgpersonrelationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='collection.Person'),
        ),
        migrations.AlterField(
            model_name='orgpersonrelationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='collection.Organization'),
        ),
        migrations.DeleteModel(
            name='Work',
        ),
        migrations.AddField(
            model_name='source',
            name='website',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Website'),
        ),
    ]
