# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collection', '0005_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateattr',
            name='content_type',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='dateattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descriptionattr',
            name='content_type',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='descriptionattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
