# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collection', '0005_auto_20160719_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateattr',
            name='source',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='content_type',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='source',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
