# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_altnameattr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='categories',
            field=models.ManyToManyField(blank=True, to='collection.OrganizationCategory'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='related_organizations',
            field=models.ManyToManyField(blank=True, help_text='Select or create a related Organization.', through='collection.OrgOrgRelationship', to='collection.Organization'),
        ),
    ]
