# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20160713_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('source_url', models.URLField()),
                ('source_accessed', models.DateField(default=django.utils.timezone.now)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NameAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('source_url', models.URLField()),
                ('source_accessed', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('source_url', models.URLField()),
                ('source_accessed', models.DateField(default=django.utils.timezone.now)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='date',
            name='source',
        ),
        migrations.RemoveField(
            model_name='name',
            name='source',
        ),
        migrations.RemoveField(
            model_name='place',
            name='source',
        ),
        migrations.AlterField(
            model_name='organization',
            name='dates',
            field=models.ManyToManyField(to='collection.DateAttr'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.NameAttr'),
        ),
        migrations.AlterField(
            model_name='person',
            name='dates',
            field=models.ManyToManyField(to='collection.DateAttr'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='dates',
            field=models.ManyToManyField(to='collection.DateAttr'),
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
