# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 21:00
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20160802_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
