# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20160721_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 22, 6, 36, 43, 763936, tzinfo=utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entity',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 22, 6, 36, 55, 991877, tzinfo=utc), verbose_name='Modified'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 22, 6, 37, 15, 184117, tzinfo=utc), verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 7, 22, 6, 37, 17, 244959, tzinfo=utc), verbose_name='Modified'),
            preserve_default=False,
        ),
    ]
