# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20160719_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_accessed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='category',
            field=models.CharField(choices=[('INCORPORATED', 'Incorporation'), ('TERMINATED', 'Termination'), ('BEGUN', 'Birth'), ('ENDED', 'Death')], max_length=50),
        ),
    ]
