# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20160713_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateattr',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='nameattr',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='nameattr',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='source',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='source_url',
            field=models.URLField(blank=True),
        ),
    ]
