# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_remove_source_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgpersonrelationship',
            old_name='parent',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='orgpersonrelationship',
            old_name='child',
            new_name='person',
        ),
    ]
