# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20160803_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, help_text='Provide the canonical physical address for this Organization.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='Provide the canonical website URL for this Organization.', null=True, unique=True),
        ),
    ]
