# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collection', '0008_auto_20160722_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltNameAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'verbose_name_plural': 'names',
                'verbose_name': 'name',
            },
        ),
        migrations.CreateModel(
            name='IdentifierAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('identifier', models.CharField(max_length=200)),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'verbose_name_plural': 'identifiers',
                'verbose_name': 'identifier',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('slug', models.SlugField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.License')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='website',
            name='url',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='category',
            field=models.CharField(choices=[('START', 'Start'), ('END', 'End')], default='START', max_length=50),
        ),
    ]
