# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20160713_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNameAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_accessed', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.DeleteModel(
            name='NameAttr',
        ),
        migrations.AddField(
            model_name='organizationnameattr',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Organization'),
        ),
    ]
