# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20160719_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='body',
        ),
        migrations.RemoveField(
            model_name='source',
            name='name',
        ),
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
    ]
