# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0009_auto_20160713_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationnameattr',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='collection.Organization'),
        ),
    ]
