# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collection', '0009_auto_20160723_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('phone', models.CharField(max_length=200)),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'verbose_name_plural': 'phones',
                'verbose_name': 'phone',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('slug', models.SlugField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('hue', models.PositiveIntegerField()),
                ('saturation', models.PositiveIntegerField()),
                ('lightness', models.PositiveIntegerField()),
                ('alpha', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=200)),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'verbose_name_plural': 'emails',
                'verbose_name': 'email',
            },
        ),
        migrations.CreateModel(
            name='ImageAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'verbose_name_plural': 'images',
                'verbose_name': 'image',
            },
        ),
        migrations.CreateModel(
            name='PhoneAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('phone', models.CharField(max_length=200)),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'verbose_name_plural': 'phones',
                'verbose_name': 'phone',
            },
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlaceAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('altitude', models.DecimalField(decimal_places=2, max_digits=10)),
                ('radius', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'verbose_name_plural': 'places',
                'verbose_name': 'place',
            },
        ),
        migrations.CreateModel(
            name='VersionAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('source_accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(default=39, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source')),
            ],
            options={
                'verbose_name_plural': 'versions',
                'verbose_name': 'version',
            },
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='date',
        ),
    ]
