# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20160723_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressattr',
            name='phone',
        ),
        migrations.AddField(
            model_name='addressattr',
            name='city',
            field=models.CharField(default='example', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressattr',
            name='country',
            field=models.CharField(default='example', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressattr',
            name='postal_code',
            field=models.CharField(default='example', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressattr',
            name='state_region',
            field=models.CharField(default='example', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressattr',
            name='street',
            field=models.TextField(default='example'),
            preserve_default=False,
        ),
    ]
