# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20160719_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='source',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='source',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
