# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20160804_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='summary',
            field=models.CharField(blank=True, help_text='Provide a short, precise, summary of this Organization.', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, help_text='Provide the canonical physical address for this Organization.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, help_text='Provide the canonical website URL for this Organization.'),
        ),
    ]
