# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20160723_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='addressattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='altnameattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='altnameattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='emailattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='emailattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='identifierattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='identifierattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='imageattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='imageattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='phoneattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='phoneattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='placeattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='placeattr',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='versionattr',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='versionattr',
            name='object_id',
        ),
    ]
