# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0011_auto_20160804_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='summary',
        ),
        migrations.AddField(
            model_name='organization',
            name='intro',
            field=models.CharField(blank=True, help_text='Provide a short, precise, summary of this Organization.', max_length=250),
        ),
    ]
