# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('collection', '0012_auto_20160719_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateattr',
            name='source',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='source',
        ),
        migrations.RemoveField(
            model_name='source',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='object_id',
        ),
        migrations.AddField(
            model_name='source',
            name='attribute_content_type',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='source',
            name='attribute_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='work_content_type',
            field=models.ForeignKey(default=47, on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='source',
            name='work_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
