# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20160719_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='attribute_content_type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='attribute_id',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_accessed',
        ),
        migrations.RemoveField(
            model_name='source',
            name='work_content_type',
        ),
        migrations.RemoveField(
            model_name='source',
            name='work_id',
        ),
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dateattr',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AddField(
            model_name='dateattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='descriptionattr',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AddField(
            model_name='descriptionattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='source',
            name='citation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='slug',
            field=models.SlugField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
