# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0013_auto_20160724_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='alpha',
        ),
        migrations.RemoveField(
            model_name='color',
            name='hue',
        ),
        migrations.RemoveField(
            model_name='color',
            name='lightness',
        ),
        migrations.RemoveField(
            model_name='color',
            name='saturation',
        ),
        migrations.AddField(
            model_name='color',
            name='a',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Select a Alpha/Transparency as a decimal percentage.', max_digits=3),
        ),
        migrations.AddField(
            model_name='color',
            name='h',
            field=models.PositiveIntegerField(default=0, help_text='Select a Hue from 0-255.'),
        ),
        migrations.AddField(
            model_name='color',
            name='l',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Select a Lightness/Brightness as a decimal percentage.', max_digits=3),
        ),
        migrations.AddField(
            model_name='color',
            name='s',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Select a Saturation as a decimal percentage.', max_digits=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(help_text='Please work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(help_text='Please work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='license',
            name='slug',
            field=models.SlugField(help_text='Please work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Please work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(help_text='Please work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='slug',
            field=models.SlugField(help_text='Please work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='source',
            name='book',
            field=models.ForeignKey(blank=True, help_text='Select if source is a book.', on_delete=django.db.models.deletion.CASCADE, to='collection.Book'),
        ),
        migrations.AlterField(
            model_name='source',
            name='content_type',
            field=models.CharField(choices=[('WEBSITE', 'website'), ('BOOK', 'book')], help_text='Select a Work model class referenced by this citation.', max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='website',
            field=models.ForeignKey(blank=True, help_text='Select if source is a website.', on_delete=django.db.models.deletion.CASCADE, to='collection.Website'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(help_text='Please work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(help_text='Please work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
    ]
