# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_auto_20160719_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='source',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
