# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0014_auto_20160726_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressattr',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary'), ('WORK', 'work'), ('HOME', 'home'), ('INFODESK', 'main information desk')], default='PRIMARY', help_text='What type of address is this?', max_length=50),
        ),
        migrations.AddField(
            model_name='emailattr',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary'), ('WORK', 'work'), ('HOME', 'home'), ('INFODESK', 'main information desk')], default='PRIMARY', help_text='What type of email address is this?', max_length=50),
        ),
        migrations.AddField(
            model_name='phoneattr',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary'), ('WORK', 'work'), ('HOME', 'home'), ('INFODESK', 'main information desk')], default='PRIMARY', help_text='What type of phone number is this?', max_length=50),
        ),
        migrations.AlterField(
            model_name='addressattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='addressattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='addressattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='addressattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='addressattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='altnameattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='altnameattr',
            name='name',
            field=models.CharField(help_text='What other names was the item known by?', max_length=200),
        ),
        migrations.AlterField(
            model_name='altnameattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='altnameattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='altnameattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='altnameattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(help_text='Work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug',
            field=models.SlugField(help_text='Work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='category',
            field=models.CharField(choices=[('START', 'Birth'), ('END', 'Death')], default='START', help_text='What type of date is this?', max_length=50),
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='dateattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='descriptionattr',
            name='body',
            field=models.TextField(help_text='Provide a date snippet from the original context.'),
        ),
        migrations.AlterField(
            model_name='descriptionattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='descriptionattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='descriptionattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='descriptionattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='descriptionattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='emailattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='emailattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='emailattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='emailattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='emailattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='identifierattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='identifierattr',
            name='identifier',
            field=models.CharField(help_text='An identifier from the original context, like a DOI, LoC, or museum accession number.', max_length=200),
        ),
        migrations.AlterField(
            model_name='identifierattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='identifierattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='identifierattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='identifierattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='imageattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='imageattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='imageattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='imageattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='imageattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='license',
            name='slug',
            field=models.SlugField(help_text='Work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(help_text='Work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='phoneattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='phoneattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='phoneattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='phoneattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='phoneattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='photograph',
            name='slug',
            field=models.SlugField(help_text='Work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='altitude',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Provide an altitude, in meters above sea level.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='latitude',
            field=models.DecimalField(decimal_places=7, help_text='Provide a latitude of the place centroid.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='longitude',
            field=models.DecimalField(decimal_places=7, help_text='Provide a longitude of the place centroid.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='radius',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Allows a simple approximate area for this point, in meters.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='placeattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='slug',
            field=models.SlugField(help_text='Work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
        migrations.AlterField(
            model_name='versionattr',
            name='content_type',
            field=models.ForeignKey(default=39, help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='versionattr',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='Provide the actual object ID of the generic relation within the table of the Content Type.', null=True),
        ),
        migrations.AlterField(
            model_name='versionattr',
            name='sequence',
            field=models.PositiveIntegerField(default=0, help_text='Provide a display order.'),
        ),
        migrations.AlterField(
            model_name='versionattr',
            name='source',
            field=models.ForeignKey(blank=True, help_text='Provide a citation for this attribute.', null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Source'),
        ),
        migrations.AlterField(
            model_name='versionattr',
            name='source_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='When was this source consulted.'),
        ),
        migrations.AlterField(
            model_name='website',
            name='slug',
            field=models.SlugField(help_text='Work from the general to the specific, e.g. <em>last-name-first-name</em>.', max_length=200),
        ),
    ]
