# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0015_auto_20160719_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.CharField(choices=[('WEBSITE', 'Website'), ('BOOK', 'Book'), ('TOOL', 'Tool')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
        migrations.AlterModelOptions(
            name='dateattr',
            options={'verbose_name': 'date', 'verbose_name_plural': 'dates'},
        ),
        migrations.AlterModelOptions(
            name='descriptionattr',
            options={'verbose_name': 'description', 'verbose_name_plural': 'descriptions'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='source',
        ),
        migrations.RemoveField(
            model_name='dateattr',
            name='source_accessed',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='source',
        ),
        migrations.RemoveField(
            model_name='descriptionattr',
            name='source_accessed',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
