# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0017_auto_20160720_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('WEBSITE', 'Website'), ('BOOK', 'Book'), ('TOOL', 'Tool')], default='WEBSITE', max_length=50),
        ),
    ]
