# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='articleindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='articleindexpagerelatedlink',
            name='link_page',
        ),
        migrations.RemoveField(
            model_name='articleindexpagerelatedlink',
            name='page',
        ),
        migrations.DeleteModel(
            name='ArticleIndexPage',
        ),
        migrations.DeleteModel(
            name='ArticleIndexPageRelatedLink',
        ),
    ]
