# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogindexpage_blogindexrelatedlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexrelatedlink',
            name='title',
            field=models.CharField(help_text='Link title', max_length=200),
        ),
    ]
