# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], default='PRIMARY', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('dates', models.ManyToManyField(related_name='items', to='register.DateAttribute')),
            ],
        ),
        migrations.AddField(
            model_name='dateattribute',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register.Item'),
        ),
    ]
