# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.Item')),
            ],
            options={
                'abstract': False,
            },
            bases=('register.item',),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], default='PRIMARY', max_length=20),
        ),
    ]
