# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160712_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.Item')),
            ],
            bases=('register.item',),
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='item_ptr',
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], default='PRIMARY', max_length=20),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.Entity')),
                ('name_first', models.CharField(max_length=255)),
                ('name_last', models.CharField(max_length=255)),
            ],
            bases=('register.entity',),
        ),
        migrations.AddField(
            model_name='organization',
            name='entity_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.Entity'),
            preserve_default=False,
        ),
    ]
