# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160712_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dates',
            field=models.ManyToManyField(blank=True, related_name='items', to='register.DateAttribute'),
        ),
    ]
