# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 21:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltNameAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('object_id', models.PositiveIntegerField(help_text='Provide the actual object ID of the generic relation within the table of the Content Type.')),
                ('name', models.CharField(help_text="Select an alternate Name, e.g. the abbreviation 'OCLC'.", max_length=200)),
                ('category', models.CharField(choices=[('ABBREVIATION', 'abbreviation'), ('NICKNAME', 'nickname')], default='ABBREVIATION', help_text='In what category is this name?', max_length=50)),
                ('content_type', models.ForeignKey(help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'alternate name',
                'verbose_name_plural': 'alternate names',
            },
        ),
        migrations.CreateModel(
            name='EventAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('object_id', models.PositiveIntegerField(help_text='Provide the actual object ID of the generic relation within the table of the Content Type.')),
                ('year', models.PositiveIntegerField(help_text='During what year did the event happen?', validators=[django.core.validators.MaxValueValidator(9999)])),
                ('category', models.CharField(choices=[('INCORPORATION', 'incorporation'), ('TERMINATION', 'termination')], default='INCORPORATION', help_text='What is this event?', max_length=50)),
                ('content_type', models.ForeignKey(help_text='Provide the model name for the generic relation.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('slug', models.SlugField(help_text='Work from the general to the specific, e.g. <em>last-name-first-name</em>.  If this is a generic name, affix with a parent acronym, e.g. <em>aic-prints-drawings</em>.', max_length=200, unique=True)),
                ('name', models.CharField(help_text='Provide the canonical name for this Organization.', max_length=200, unique=True)),
                ('intro', models.CharField(blank=True, help_text='Provide a short, precise, summary of this Organization.', max_length=250)),
                ('website', models.URLField(blank=True, help_text='Provide the canonical website URL for this Organization.')),
                ('address', models.TextField(blank=True, help_text='Provide the canonical physical address for this Organization.')),
                ('nonprofit', models.BooleanField(default=True, help_text='Select whether or not this organization is organized as a not-for-profit entity.')),
                ('scope', models.IntegerField(choices=[(0, 'closed'), (1, 'local'), (2, 'regional'), (3, 'national'), (4, 'international')], default=2, help_text="What is the level of influence, reach, or exposure of this Organization within its industry?  This is a subjective rubric intended to imply scale or importance: an individual gallery, a supermarket, or a high school would be 'local'; a holding company, a city arts center, or a college would be 'regional'; most large corporations, museums, or state universities would be 'national'.  Only the largest, most famous entities, e.g. Microsoft, the Louvre, the New York Philharmonic, or Harvard University, are considered 'international'.")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('category', models.CharField(choices=[('ARCHIVE', 'archive'), ('ASSOCIATION', 'center'), ('CONSORTIUM', 'consortium'), ('CORPORATION', 'corporation'), ('FOUNDATION', 'foundation'), ('GALLERY', 'gallery'), ('LIBRARY', 'library'), ('MUSEUM', 'museum'), ('SCHOOL', 'school')], default='LIBRARY', help_text='What type of organization?', max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrgOrgRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('DEPARTMENT', 'is department of'), ('LOCATED', 'is located in'), ('MEMBER', 'is member of'), ('OWNED', 'is owned by'), ('PART', 'is part of')], default='DEPARTMENT', help_text='Select a qualifier for this relationship.', max_length=50)),
                ('child', models.ForeignKey(help_text='Select a child Organization.', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Organization')),
                ('parent', models.ForeignKey(help_text='Select a parent Organization.', on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='catalog.Organization')),
            ],
            options={
                'verbose_name': 'organization relationship',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='categories',
            field=models.ManyToManyField(blank=True, to='catalog.OrganizationCategory'),
        ),
        migrations.AddField(
            model_name='organization',
            name='related_organizations',
            field=models.ManyToManyField(blank=True, help_text='Select or create a related Organization.', through='catalog.OrgOrgRelationship', to='catalog.Organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
