# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectoryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DirectoryIndexRelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('title', models.CharField(help_text='Link title', max_length=200)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('START', 'start date'), ('END', 'end date')], default='PRIMARY', max_length=20)),
                ('source', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('category', models.CharField(choices=[('LIBRARY', 'Library'), ('ARCHIVE', 'Archive'), ('MUSEUM', 'Museum'), ('SCHOOL', 'School'), ('COMPANY', 'Company'), ('CONSORTIUM', 'Consortium')], default='LIBRARY', max_length=23)),
                ('for_profit', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('INACTIVE', 'Inactive/Closed'), ('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], default='LOCAL', max_length=23)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OrganizationPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('HOME', 'work phone'), ('WORK', 'home phone')], default='PRIMARY', max_length=20)),
                ('source', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('number', models.CharField(max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_phones', to='directory.OrganizationPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('START', 'start date'), ('END', 'end date')], default='PRIMARY', max_length=20)),
                ('source', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name_last', models.CharField(max_length=200, verbose_name='First Name')),
                ('name_first', models.CharField(max_length=200, verbose_name='Last Name')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('START', 'start date'), ('END', 'end date')], default='PRIMARY', max_length=20)),
                ('source', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('accessed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_phones', to='directory.PersonPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='persondates',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_dates', to='directory.PersonPage'),
        ),
        migrations.AddField(
            model_name='organizationdates',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_dates', to='directory.OrganizationPage'),
        ),
        migrations.AddField(
            model_name='directoryindexrelatedlink',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='directoryindexrelatedlink',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='directory.DirectoryIndexPage'),
        ),
    ]
