# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0028_merge'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('category', models.CharField(choices=[('LIBRARY', 'Library'), ('ARCHIVE', 'Archive'), ('MUSEUM', 'Museum'), ('SCHOOL', 'School'), ('COMPANY', 'Company'), ('CONSORTIUM', 'Consortium')], default='LIBRARY', max_length=23)),
                ('for_profit', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('INACTIVE', 'Inactive/Closed'), ('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], default='LOCAL', max_length=23)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OrganizationPageRelatedLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_links', to='directory.OrganizationPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
