# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('directory', '0002_directoryindexpage_directoryindexrelatedlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='Post Date')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('type', models.CharField(choices=[('CORPORATION', 'Company'), ('CONSORTIUM', 'Consortium'), ('DEPARTMENT', 'Department or Unit')], max_length=23)),
                ('for_profit', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('INACTIVE', 'closed/inactive/defunct'), ('LOCAL', 'local'), ('REGIONAL', 'regional'), ('NATIONAL', 'national'), ('INTERNATIONAL', 'international')], default='LOCAL', max_length=23)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PersonPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='Post Date')),
                ('body', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('name_last', models.CharField(max_length=255, verbose_name='First Name')),
                ('name_first', models.CharField(max_length=255, verbose_name='Last Name')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='entitypage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='workpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='EntityPage',
        ),
        migrations.DeleteModel(
            name='WorkPage',
        ),
    ]
