# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_auto_20160705_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationpage',
            name='type',
        ),
        migrations.AlterField(
            model_name='organizationpage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Post Date'),
        ),
        migrations.AlterField(
            model_name='organizationpage',
            name='scope',
            field=models.CharField(choices=[('INACTIVE', 'Inactive/Closed'), ('LOCAL', 'Local'), ('REGIONAL', 'Regional'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], default='LOCAL', max_length=23),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Post Date'),
        ),
    ]
