# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_personpagerelateddates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='organizationpagerelateddates',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], default='START', max_length=20),
        ),
        migrations.AlterField(
            model_name='personpagerelateddates',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary')], default='START', max_length=20),
        ),
    ]
