# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_auto_20160713_0221'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPageRelatedPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('HOME', 'work phone'), ('WORK', 'home phone')], default='PRIMARY', max_length=20)),
                ('number', models.CharField(max_length=50)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_phones', to='directory.OrganizationPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonPageRelatedPhones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('START', 'start date'), ('END', 'end date')], default='PRIMARY', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_phones', to='directory.PersonPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='organizationpagerelateddates',
            name='category',
            field=models.CharField(choices=[('START', 'start date'), ('END', 'end date')], default='PRIMARY', max_length=20),
        ),
        migrations.AlterField(
            model_name='personpagerelateddates',
            name='category',
            field=models.CharField(choices=[('START', 'start date'), ('END', 'end date')], default='PRIMARY', max_length=20),
        ),
    ]
