# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_auto_20160713_0325'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationPageRelatedDates',
            new_name='OrganizationDates',
        ),
        migrations.RenameModel(
            old_name='OrganizationPageRelatedPhones',
            new_name='OrganizationPhones',
        ),
        migrations.RenameModel(
            old_name='PersonPageRelatedDates',
            new_name='PersonDates',
        ),
        migrations.RenameModel(
            old_name='PersonPageRelatedPhones',
            new_name='PersonPhones',
        ),
    ]
