# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20160713_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='accessed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='citation',
            name='body',
            field=models.TextField(default='Test citation.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citation',
            name='url',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationdates',
            name='citation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.Citation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationphones',
            name='citation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.Citation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persondates',
            name='citation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.Citation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personphones',
            name='citation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='directory.Citation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='directoryindexrelatedlink',
            name='title',
            field=models.CharField(help_text='Link title', max_length=200),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='name_first',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='personpage',
            name='name_last',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
    ]
