# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_auto_20160713_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdates',
            name='citation_accessed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizationdates',
            name='citation_url',
            field=models.URLField(default='http://example.com/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationphones',
            name='citation_accessed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizationphones',
            name='citation_url',
            field=models.URLField(default='http://example.com/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persondates',
            name='citation_accessed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='persondates',
            name='citation_url',
            field=models.URLField(default='http://example.com/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personphones',
            name='citation_accessed',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='personphones',
            name='citation_url',
            field=models.URLField(default='http://example.com/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organizationdates',
            name='citation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organizationphones',
            name='citation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='persondates',
            name='citation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='personphones',
            name='citation',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
    ]
