# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 04:05
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_auto_20160713_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationdates',
            name='citation',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='organizationphones',
            name='citation',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='persondates',
            name='citation',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='personphones',
            name='citation',
            field=wagtail.wagtailcore.fields.RichTextField(),
        ),
    ]
