# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_auto_20160713_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationdates',
            name='citation_url',
        ),
        migrations.RemoveField(
            model_name='organizationphones',
            name='citation_url',
        ),
        migrations.RemoveField(
            model_name='persondates',
            name='citation_url',
        ),
        migrations.RemoveField(
            model_name='personphones',
            name='citation_url',
        ),
        migrations.AlterField(
            model_name='organizationdates',
            name='citation',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationdates',
            name='citation_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizationphones',
            name='citation',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizationphones',
            name='citation_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='persondates',
            name='citation',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='persondates',
            name='citation_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='personphones',
            name='citation',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='personphones',
            name='citation_accessed',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
