# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_auto_20160713_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationdates',
            old_name='citation_accessed',
            new_name='accessed',
        ),
        migrations.RenameField(
            model_name='organizationdates',
            old_name='citation',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='organizationphones',
            old_name='citation_accessed',
            new_name='accessed',
        ),
        migrations.RenameField(
            model_name='organizationphones',
            old_name='citation',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='persondates',
            old_name='citation_accessed',
            new_name='accessed',
        ),
        migrations.RenameField(
            model_name='persondates',
            old_name='citation',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='personphones',
            old_name='citation_accessed',
            new_name='accessed',
        ),
        migrations.RenameField(
            model_name='personphones',
            old_name='citation',
            new_name='source',
        ),
    ]
